# üìç Îç∞Ïù¥ÌÑ∞Ï∂îÍ∞Ä
### ‚úÖ ÏóëÏÖÄÎ°ú Ïó¥Í∏∞
: ```pd.read_excel('ÌååÏùºÎ™Ö.xlsx', index_col='column')```

In [1]:
import pandas as pd

df = pd.read_excel('score.xlsx', index_col='ÏßÄÏõêÎ≤àÌò∏') # index ÏÑ§Ï†ï
df

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§   Íµ≠Ïñ¥   ÏòÅÏñ¥   ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197   90   85  100  95  85      Python
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184   40   35   50  55  25        Java
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168   80   75   70  80  75  Javascript
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187   40   60   70  75  80         NaN
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188   15   20   10  35  10         NaN
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202   80  100   95  85  80           C
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188   55   65   45  40  35      PYTHON
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  100   85   90  95  95          C#

### ‚úÖ Row Ï∂îÍ∞Ä
: ```df.loc['index']=[list]```

In [2]:
df.loc['9Î≤à'] = ['Ïù¥Ï†ïÌôò', 'Ìï¥ÎÇ®Í≥†', 184, 90, 90, 90, 90, 90, 'Kotlin']
df

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§   Íµ≠Ïñ¥   ÏòÅÏñ¥   ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197   90   85  100  95  85      Python
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184   40   35   50  55  25        Java
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168   80   75   70  80  75  Javascript
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187   40   60   70  75  80         NaN
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188   15   20   10  35  10         NaN
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202   80  100   95  85  80           C
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188   55   65   45  40  35      PYTHON
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  100   85   90  95  95          C#
9Î≤à    Ïù¥Ï†ïÌôò  Ìï¥ÎÇ®Í≥†  184   90   90   90  90  90      Kotlin

### ‚úÖ Column Ï∂îÍ∞Ä
: ```df['new_column']=data```

In [3]:
df['Ï¥ùÌï©'] = df['Íµ≠Ïñ¥'] + df['ÏòÅÏñ¥'] + df['ÏàòÌïô'] + df['Í≥ºÌïô'] + df['ÏÇ¨Ìöå']
df

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§   Íµ≠Ïñ¥   ÏòÅÏñ¥   ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞   Ï¥ùÌï©
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197   90   85  100  95  85      Python  455
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184   40   35   50  55  25        Java  205
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168   80   75   70  80  75  Javascript  380
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187   40   60   70  75  80         NaN  325
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188   15   20   10  35  10         NaN   90
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202   80  100   95  85  80           C  440
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188   55   65   45  40  35      PYTHON  240
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  100   85   90  95  95          C#  465
9Î≤à    Ïù¥Ï†ïÌôò  Ìï¥ÎÇ®Í≥†  184   90   90   90  90  90      Kotlin  450

In [4]:
df['Í≤∞Í≥º'] = 'Fail'
df

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§   Íµ≠Ïñ¥   ÏòÅÏñ¥   ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞   Ï¥ùÌï©    Í≤∞Í≥º
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197   90   85  100  95  85      Python  455  Fail
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184   40   35   50  55  25        Java  205  Fail
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168   80   75   70  80  75  Javascript  380  Fail
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187   40   60   70  75  80         NaN  325  Fail
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188   15   20   10  35  10         NaN   90  Fail
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202   80  100   95  85  80           C  440  Fail
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188   55   65   45  40  35      PYTHON  240  Fail
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  100   85   90  95  95          C#  465  Fail
9Î≤à    Ïù¥Ï†ïÌôò  Ìï¥ÎÇ®Í≥†  184   90   90   90  90  90      Kotlin  450  Fail

### ‚úÖ Ï°∞Í±¥, Îç∞Ïù¥ÌÑ∞ÏàòÏ†ï ÏùëÏö©

In [5]:
df.loc[df['Ï¥ùÌï©'] > 400, 'Í≤∞Í≥º'] = 'Pass' # Ï¥ùÌï©Ïù¥ 400Î≥¥Îã§ ÌÅ∞ Îç∞Ïù¥ÌÑ∞Ïóê ÎåÄÌï¥ÏÑú Í≤∞Í≥ºÎ•º PassÎ°ú ÏóÖÎç∞Ïù¥Ìä∏
df

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§   Íµ≠Ïñ¥   ÏòÅÏñ¥   ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞   Ï¥ùÌï©    Í≤∞Í≥º
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197   90   85  100  95  85      Python  455  Pass
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184   40   35   50  55  25        Java  205  Fail
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168   80   75   70  80  75  Javascript  380  Fail
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187   40   60   70  75  80         NaN  325  Fail
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188   15   20   10  35  10         NaN   90  Fail
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202   80  100   95  85  80           C  440  Pass
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188   55   65   45  40  35      PYTHON  240  Fail
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  100   85   90  95  95          C#  465  Pass
9Î≤à    Ïù¥Ï†ïÌôò  Ìï¥ÎÇ®Í≥†  184   90   90   90  90  90      Kotlin  450  Pass

# üìç Îç∞Ïù¥ÌÑ∞ÏÇ≠Ï†ú
### ‚úÖ Column ÏÇ≠Ï†ú
: ```df.drop(columns=[column_list])```

In [6]:
df.drop(columns=['Ï¥ùÌï©']) # Ï¥ùÌï© columnÏùÑ ÏÇ≠Ï†ú

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§   Íµ≠Ïñ¥   ÏòÅÏñ¥   ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞    Í≤∞Í≥º
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197   90   85  100  95  85      Python  Pass
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184   40   35   50  55  25        Java  Fail
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168   80   75   70  80  75  Javascript  Fail
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187   40   60   70  75  80         NaN  Fail
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188   15   20   10  35  10         NaN  Fail
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202   80  100   95  85  80           C  Pass
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188   55   65   45  40  35      PYTHON  Fail
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  100   85   90  95  95          C#  Pass
9Î≤à    Ïù¥Ï†ïÌôò  Ìï¥ÎÇ®Í≥†  184   90   90   90  90  90      Kotlin  Pass

In [7]:
df.drop(columns=['Íµ≠Ïñ¥', 'ÏòÅÏñ¥', 'ÏàòÌïô'], inplace=True)
df

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞   Ï¥ùÌï©    Í≤∞Í≥º
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197  95  85      Python  455  Pass
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184  55  25        Java  205  Fail
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168  80  75  Javascript  380  Fail
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187  75  80         NaN  325  Fail
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188  35  10         NaN   90  Fail
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202  85  80           C  440  Pass
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188  40  35      PYTHON  240  Fail
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  95  95          C#  465  Pass
9Î≤à    Ïù¥Ï†ïÌôò  Ìï¥ÎÇ®Í≥†  184  90  90      Kotlin  450  Pass

### ‚úÖ Row ÏÇ≠Ï†ú
: ```df.drop(index=[row_list])```

In [8]:
df.drop(index='4Î≤à') # 4Î≤à ÌïôÏÉù rowÎ•º ÏÇ≠Ï†ú

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞   Ï¥ùÌï©    Í≤∞Í≥º
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197  95  85      Python  455  Pass
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184  55  25        Java  205  Fail
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168  80  75  Javascript  380  Fail
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188  35  10         NaN   90  Fail
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202  85  80           C  440  Pass
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188  40  35      PYTHON  240  Fail
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  95  95          C#  465  Pass
9Î≤à    Ïù¥Ï†ïÌôò  Ìï¥ÎÇ®Í≥†  184  90  90      Kotlin  450  Pass

In [9]:
df = pd.read_excel('score.xlsx', index_col='ÏßÄÏõêÎ≤àÌò∏')
filt = df['ÏàòÌïô'] < 80 # ÏàòÌïôÏ†êÏàò 80Ï†êÎØ∏Îßå ÌïôÏÉù ÌïÑÌÑ∞ÎßÅ
df[filt]

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§  Íµ≠Ïñ¥  ÏòÅÏñ¥  ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå        SWÌäπÍ∏∞
ÏßÄÏõêÎ≤àÌò∏
2Î≤à    Ï†ïÎåÄÎßå  Î∂ÅÏÇ∞Í≥†  184  40  35  50  55  25        Java
3Î≤à    ÏÜ°ÌÉúÏÑ≠  Î∂ÅÏÇ∞Í≥†  168  80  75  70  80  75  Javascript
4Î≤à    ÏÑúÌÉúÏõÖ  Î∂ÅÏÇ∞Í≥†  187  40  60  70  75  80         NaN
5Î≤à    Í∞ïÎ∞±Ìò∏  Î∂ÅÏÇ∞Í≥†  188  15  20  10  35  10         NaN
7Î≤à    Ìô©ÌÉúÏÇ∞  Îä•ÎÇ®Í≥†  188  55  65  45  40  35      PYTHON

In [10]:
df[filt].index

Index(['2Î≤à', '3Î≤à', '4Î≤à', '5Î≤à', '7Î≤à'], dtype='object', name='ÏßÄÏõêÎ≤àÌò∏')

In [12]:
df.drop(index=df[filt].index) # ÏàòÌïôÏ†êÏàò 80Ï†ê ÎØ∏ÎßåÏù∏ ÌïôÏÉù ÏÇ≠Ï†ú

       Ïù¥Î¶Ñ   ÌïôÍµê    ÌÇ§   Íµ≠Ïñ¥   ÏòÅÏñ¥   ÏàòÌïô  Í≥ºÌïô  ÏÇ¨Ìöå    SWÌäπÍ∏∞
ÏßÄÏõêÎ≤àÌò∏
1Î≤à    Ï±ÑÏπòÏàò  Î∂ÅÏÇ∞Í≥†  197   90   85  100  95  85  Python
6Î≤à    Î≥ÄÎçïÍ∑ú  Îä•ÎÇ®Í≥†  202   80  100   95  85  80       C
8Î≤à    Ïú§ÎåÄÌòë  Îä•ÎÇ®Í≥†  190  100   85   90  95  95      C#